// DO NOT EDIT: This file is auto-generated by generate-schema/index.ts
import { z } from "zod";
export const Notification = z.discriminatedUnion("$type", [
    z.object({ $type: z.literal("started"), version: z.string() }),
    z.object({ $type: z.literal("ipc"), message: z.string() }),
    z.object({ $type: z.literal("closed") }),
]);
export const SizeWithScale = z.object({
    height: z.number(),
    scaleFactor: z.number(),
    width: z.number(),
});
export const ResultType = z.discriminatedUnion("$type", [
    z.object({ $type: z.literal("string"), value: z.string() }),
    z.object({ $type: z.literal("boolean"), value: z.boolean() }),
    z.object({ $type: z.literal("float"), value: z.number() }),
    z.object({ $type: z.literal("size"), value: SizeWithScale }),
]);
export const Response = z.discriminatedUnion("$type", [
    z.object({ $type: z.literal("ack"), id: z.number().int() }),
    z.object({
        $type: z.literal("result"),
        id: z.number().int(),
        result: ResultType,
    }),
    z.object({
        $type: z.literal("err"),
        id: z.number().int(),
        message: z.string(),
    }),
]);
export const Message = z.discriminatedUnion("$type", [
    z.object({ $type: z.literal("notification"), data: Notification }),
    z.object({ $type: z.literal("response"), data: Response }),
]);
export const Content = z.union([
    z.object({
        headers: z.record(z.string(), z.string()).optional(),
        url: z.string(),
    }),
    z.object({ html: z.string(), origin: z.string() }),
]);
export const Size = z.object({
    height: z.number(),
    width: z.number(),
});
export const WindowSizeStates = z.enum([
    "maximized",
    "fullscreen",
]);
export const WindowSize = z.union([
    WindowSizeStates,
    Size,
]);
export const Options = z.object({
    acceptFirstMouse: z.boolean().optional(),
    autoplay: z.boolean().optional(),
    clipboard: z.boolean().optional(),
    decorations: z.boolean().optional(),
    devtools: z.boolean().optional(),
    focused: z.boolean().optional(),
    incognito: z.boolean().optional(),
    initializationScript: z.string(),
    ipc: z.boolean().optional(),
    load: Content.optional(),
    size: WindowSize.optional(),
    title: z.string(),
    transparent: z.boolean().optional(),
    userAgent: z.string(),
});
export const Request = z.discriminatedUnion("$type", [
    z.object({ $type: z.literal("getVersion"), id: z.number().int() }),
    z.object({ $type: z.literal("eval"), id: z.number().int(), js: z.string() }),
    z.object({
        $type: z.literal("setTitle"),
        id: z.number().int(),
        title: z.string(),
    }),
    z.object({ $type: z.literal("getTitle"), id: z.number().int() }),
    z.object({
        $type: z.literal("setVisibility"),
        id: z.number().int(),
        visible: z.boolean(),
    }),
    z.object({ $type: z.literal("isVisible"), id: z.number().int() }),
    z.object({ $type: z.literal("openDevTools"), id: z.number().int() }),
    z.object({
        $type: z.literal("getSize"),
        id: z.number().int(),
        include_decorations: z.boolean().optional(),
    }),
    z.object({ $type: z.literal("setSize"), id: z.number().int(), size: Size }),
    z.object({
        $type: z.literal("fullscreen"),
        fullscreen: z.boolean().optional(),
        id: z.number().int(),
    }),
    z.object({
        $type: z.literal("maximize"),
        id: z.number().int(),
        maximized: z.boolean().optional(),
    }),
    z.object({
        $type: z.literal("minimize"),
        id: z.number().int(),
        minimized: z.boolean().optional(),
    }),
    z.object({
        $type: z.literal("loadHtml"),
        html: z.string(),
        id: z.number().int(),
        origin: z.string().optional(),
    }),
    z.object({
        $type: z.literal("loadUrl"),
        headers: z.record(z.string(), z.string()).optional(),
        id: z.number().int(),
        url: z.string(),
    }),
]);
//# sourceMappingURL=schemas.js.map